---
- hosts: localhost
  gather_facts: false
  roles:
    - generate-zuul-manifest
    - role: upload-logs
      vars:
        # use your dns or ip address here
        zuul_log_url: "http://zuul.tibeer.de:8000"
